trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: 'azure-sub-conn'  # your Azure RM service connection name

stages:
- stage: Terraform
  jobs:
  - job: TerraformInitPlanApply
    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az account show
      displayName: 'Azure Account Info'

    - script: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
        unzip terraform_1.5.6_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform version
      displayName: 'Install Terraform'

    - script: |
        terraform init -reconfigure
      displayName: 'Terraform Init'

    - script: |
        terraform plan -out=tfplan
      displayName: 'Terraform Plan'

    - script: |
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'
