trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: 'azure-sub-conn'  # your Azure RM service connection name

stages:
- stage: Terraform
  jobs:
  - job: TerraformInitPlanApply
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az account show

          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
          unzip terraform_1.5.6_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform version

          terraform init -reconfigure
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
      displayName: 'Terraform Init, Plan, Apply'
